baseURL = 'https://bex.computer/'
languageCode = 'en-us'
title = 'bex.computer'
theme = "glim-midnight"


[params]
    title = "/bex"
    phrases = ["welcome", "choose your destination:"]
    links = [
    {name = "instagram", url = "https://www.instagram.com/bex.computer"},
    {name = "behance", url = "https://be.net/beccanyx"},
    {name = "github", url = "https://github.com/b3xie"},
    {name = "flickr", url = "https://www.flickr.com/people/beccanyx"},
    {name = "emai/hire me!", url = "mailto:contact@bex.computer"},
    ]
    background = "bg.mp4"
